import {BarGameType, BarType} from './bar.model';

export const BAR_TYPE_LABELS: Record<BarType, string> = {
  COCKTAIL_BAR:    'Cocktails',
  BEER_BAR:        'Bières',
  CRAFT_BEER_BAR:  'Craft beer',
  BREWPUB:         'Brewpub',
  SPIRITS_BAR:     'Spiritueux',
  WINE_BAR:        'Vins',
  DANCING_BAR:     'Dansant',
  LIVE_MUSIC_BAR:  'Musique live',
  NIGHTCLUB:       'Boîte de nuit',
  SPORTS_BAR:      'Sports',
  ARCADE_BAR:      'Arcade',
  BOARD_GAME_BAR:  'Jeux de société',
  ESPORTS_BAR:     'E-sport',
  PUB:             'Pub',
  STUDENT_BAR:     'Bar étudiant',
  LOUNGE_BAR:      'Lounge',
  GUINGUETTE:      'Guinguette',
  BRASSERIE:       'Brasserie',
  TAPAS_BAR:       'Tapas',
  COFFEE_SHOP_BAR: 'Café-bar',
  CAFE_TABAC:      'Café-tabac',
  PMU:             'PMU',
  WATERFRONT_BAR:  'Bord de l\'eau',
  TERRACE_BAR:     'Terrasse',
  ROOFTOP:         'Rooftop',
  PET_FRIENDLY:    'Bar à animaux',
};

export const GAME_TYPE_LABELS: Record<BarGameType, string> = {
  BABYFOOT:      'Baby-foot',
  DARTS_PLASTIC: 'Fléchettes plastique',
  DARTS_STEEL:   'Fléchettes acier',
  BILLIARDS:     'Billard',
  PETANQUE:      'Pétanque',
  MOLKKY:        'Mölkky',
  PALET:         'Palet',
  ARCADE:        'Arcade',
  BOARD_GAMES:   'Jeux de société',
  PING_PONG:     'Ping-pong',
  BEER_PONG:     'Beer-pong',
  FLIPPER:       'Flipper',
};
